### ISSUE TITLE
Compte à rebour sur vie éphémère

### ISSUE THREAD

**Issue by cmateo** [kreaseed/crazy_chemist#10]
Il y a un compte à rebour à côté des vie éphémères :
![eph](https://f.cloud.github.com/assets/494588/1741216/7cabf100-63de-11e3-99bb-087e3579c5cd.png)

C'est normal ? normalement ce genre de vie ne revient pas avec un compte à rebour

**Comment by bseverac** [comment]
c'est le compte à rebours de mise à zero, je l'ai enlevé quand on a 0 vie éphémère
