### ISSUE TITLE
Achat de section

### ISSUE THREAD

**Issue by cmateo** [kreaseed/crazy_chemist#12]
Après avoir fini le level 15, si je clic sur "Unlock" pour payer j'ai le message d'erreur suivant :

Couldn't Complete Purchase
We didn't receive all the information we needed from this app to complete your purchase. You haven't been charged for this purchase, so please try again. If you keep seeing this error, contact the app developer.

**Comment by bseverac** [comment]
va savoir pourquoi des fois ia un truc qui marchent, et qui se mettent mystérieusement à ne plus
